# Generated by Django 5.0.4 on 2024-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_order_email_cartorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
