# Generated by Django 5.0.4 on 2024-04-20 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_cartorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(max_length=50, null=True)),
                ('date_shipped', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.cartorder')),
                ('ship_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.order')),
            ],
        ),
    ]
