# Generated by Django 5.0.4 on 2024-04-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_order_address_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.cartorder')),
                ('prev_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.order')),
            ],
        ),
    ]
